# -*- coding: utf-8 -*-
"""Proyecto Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DYQT42d2L0fv6LbF3qk0H8tkgJi1Pik

#Importacion de Librerias
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split #Paretto 80% train - 20% test
from sklearn.preprocessing import StandardScaler, OneHotEncoder

#Modelos
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

#Metricas
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

def analyze_tips_data(df_input):
    df = df_input.copy() # Work on a copy to avoid modifying the original if passed by reference

    print("## Data Understanding (Entendiendo los datos)")
    print("\n### Información general")
    df.info()

    print("\n### Distribución de variables categóricas")
    for col in ['sex', 'smoker', 'day', 'time']:
        print(f"\n{col}:")
        print(df[col].value_counts())
        print(f"Desbalance: {df[col].value_counts().max() / len(df) * 100:.1f}% en la clase dominante")

    print("\n### Estadísticas descriptivas")
    display(df.describe(include='all'))

    print("\n### Visualización distribución de la variable objetivo (tip)")
    plt.figure(figsize=(12,4))
    plt.subplot(1,2,1)
    sns.histplot(df['tip'], bins=20, kde=True)
    plt.title('Distribución de propinas')

    plt.subplot(1,2,2)
    sns.boxplot(x=df['tip'])
    plt.title('Boxplot de propinas')
    plt.show()

    print("\n### Propinas por categorías")
    plt.figure(figsize=(16, 8))

    # Propinas por género
    plt.subplot(1, 4, 1)
    sns.boxplot(data=df, x='sex', y='tip')
    plt.title('Propinas por genero')

    # Propina por fumadores
    plt.subplot(1, 4, 2)
    sns.boxplot(data=df, x='smoker', y='tip')
    plt.title('Propina por fumadores')

    # Propinas por día
    plt.subplot(1, 4, 3)
    sns.boxplot(data=df, x='day', y='tip')
    plt.title('Propina por dia')

    # Propinas por tiempo
    plt.subplot(1, 4, 4)
    sns.boxplot(data=df, x='time', y='tip')
    plt.title('Propina por horario de comida')

    plt.tight_layout()
    plt.show()

    print("\n### Correlación entre variables numéricas")
    corr = df.corr(numeric_only=True)
    plt.figure(figsize=(8,6))
    sns.heatmap(corr, annot=True, cmap='coolwarm')
    plt.title('Matriz de Correlación')
    plt.show()

    print("\n### Análisis de relaciones entre variables")
    sns.pairplot(df)
    plt.show()

    print("\n## Visualización relación entre total bill y tip")
    plt.figure(figsize=(10, 8))
    sns.scatterplot(data=df, x='total_bill', y='tip', hue='time')
    plt.title('Total Cuenta vs Propina')
    plt.xlabel('Total Cuenta')
    plt.ylabel('Propina')
    plt.show()

    print("\n## Visualización de valores nulos por columna")
    plt.figure(figsize=(8,6))
    sns.heatmap(df.isnull(), cbar=False, cmap='Reds')
    plt.title('Valores nulos por columna')
    plt.show()

    print("\n## Preparación de los datos (Data Preparation)")
    print("\n### Codificación de variables categóricas y escalado de numéricas")
    numericos = ['total_bill', 'size']
    categoricas = ['sex', 'smoker', 'day', 'time']

    df_encoded = pd.get_dummies(df, columns=categoricas, drop_first=True)

    scaler = StandardScaler()
    df_encoded[numericos] = scaler.fit_transform(df_encoded[numericos])
    print("DataFrame después de codificación y escalado:")
    display(df_encoded.head())

    print("\n### División del dataset en entrenamiento y prueba.")
    X = df_encoded.drop('tip', axis=1)
    y = df_encoded['tip']

    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    print(f"Train: {x_train.shape}, Test: {x_test.shape}")

    print("\n## Modeling (Implementación y Entrenamiento)")
    print("\n### Entrenamiento Regresión Lineal")
    model = LinearRegression()
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

    # Evaluación
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print(f'R2 Error (Linear Regression): {r2:.2f}')
    print(f'Mean Absolute Error (Linear Regression): {mae:.2f} USD')
    print(f'Mean Squared Error (Linear Regression): {mse:.2f} USD')

    print("\n### Entrenamiento Regresión KNN")
    knn_model = KNeighborsRegressor(n_neighbors=5)

    knn_model.fit(x_train, y_train)

    y_pred_knn = knn_model.predict(x_test)

    mse_knn = mean_squared_error(y_test, y_pred_knn)
    mae_knn = mean_absolute_error(y_test, y_pred_knn)
    r2_knn = r2_score(y_test, y_pred_knn)

    print(f'R2 Error (KNN): {r2_knn:.2f}')
    print(f'Mean Absolute Error (KNN): {mae_knn:.2f} USD')
    print(f'Mean Squared Error (KNN): {mse_knn:.2f} USD')

    print("\n## Visualización de Modelos")
    plt.figure(figsize=(18,7))
    plt.subplot(1,2,1)
    sns.regplot(x=x_test['total_bill'], y=y_test, marker='o', label='Datos Reales', color='blue')
    plt.scatter(x_test['total_bill'], y_pred, color='red', label='Datos de Prediccion', alpha=0.5)
    plt.title('Total Cuenta vs Propina (Regresion Lineal)')
    plt.xlabel('Total Cuenta')
    plt.ylabel('Propina')
    plt.legend()

    plt.subplot(1,2,2)
    sns.regplot(x=x_test['total_bill'], y=y_test, marker='o', label='Datos Reales', color='blue', scatter_kws={'alpha':0.5})
    plt.scatter(x_test['total_bill'], y_pred_knn, color='green', label='Prediccion KNN', alpha=0.5)
    plt.title('Total Cuenta vs Propina (KNN)')
    plt.xlabel('Total Cuenta')
    plt.ylabel('Propina')
    plt.legend()
    plt.show()

    return {
        "linear_model": model,
        "knn_model": knn_model,
        "linear_metrics": {"mse": mse, "mae": mae, "r2": r2},
        "knn_metrics": {"mse": mse_knn, "mae": mae_knn, "r2": r2_knn}
    }

"""#Cargar Dataset"""

df = sns.load_dataset('tips')
df.head()

"""#Entendiendo los datos (Data Understanding)

##Informacion general
"""

df.info()

"""* **total_bill (Numérica - Continua):** El costo total de la comida. Intuitivamente, a mayor cuenta, mayor debería ser la propina.

* **tip (Numérica - Continua):** Nuestra Variable Objetivo (Target). Lo que queremos predecir.

* **sex (Categórica - Nominal):** Género del pagador (Male/Female).

* **smoker (Categórica - Nominal):** Si el grupo incluía fumadores o si el pagador fuma (Yes/No).

* **day (Categórica - Ordinal/Nominal):** Día de la semana.

* **time (Categórica - Nominal):** Momento del día (Lunch/Dinner).

* **size (Numérica - Discreta):** Cantidad de personas en la mesa.

##Distribucion de variables categoricas
"""

for col in ['sex', 'smoker', 'day', 'time']:
    print(f"\n{col}:")
    print(df[col].value_counts())
    print(f"Desbalance: {df[col].value_counts().max() / len(df) * 100:.1f}% en la clase dominante")

"""##Estadisticas descriptivas"""

df.describe(include='all')

"""##Visalización distribucion de la variable objetivo"""

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
sns.histplot(df['tip'], bins=20, kde=True)
plt.title('Distribución de propinas')

plt.subplot(1,2,2)
sns.boxplot(x=df['tip'])
plt.title('Boxplot de propinas')
plt.show()

plt.figure(figsize=(16, 8))

# Propinas por género
plt.subplot(1, 4, 1)
sns.boxplot(data=df, x='sex', y='tip')
plt.title('Propinas por genero')

# Propina por fumadores
plt.subplot(1, 4, 2)
sns.boxplot(data=df, x='smoker', y='tip')
plt.title('Propina por fumadores')

# Propinas por día
plt.subplot(1, 4, 3)
sns.boxplot(data=df, x='day', y='tip')
plt.title('Propina por dia')

# Propinas por tiempo
plt.subplot(1, 4, 4)
sns.boxplot(data=df, x='time', y='tip')
plt.title('Propina por horario de comida')

plt.tight_layout() # Para que no se encimen los textos
plt.show()

#Correlación
corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

#Análisis de relaciones entre variables qué variables afectan más la propina, cuáles tienen relación fuerte, cuáles podrían servir mejor para el modelo
sns.pairplot(df)
plt.show()

"""##Visualización relacion entre total bill y tip"""

plt.figure(figsize=(10, 8))
sns.scatterplot(data=df, x='total_bill', y='tip', hue='time')
plt.title('Total Cuenta vs Propina')
plt.xlabel('Total Cuenta')
plt.ylabel('Propina')
plt.show()

"""##Visualizacion de valores nulos por columna"""

sns.heatmap(df.isnull(), cbar=False, cmap='Reds')
plt.title('Valores nulos por columna')
plt.show()

"""##Conclusiones del análisis inicial

* No hay valores nulos en ninguna columna
* Las variables categoricas son: `sex`, `smoker`, `day`, `time`
* La variable `tip` tiene una asimetria positiva a la derecha, lo que indica que hay clientes que dieron mucha propina.
* `total_bill` y `tip` muestran una correlacion positiva

#Preparación de los datos (Data Preparetion)

##Codificación de variables categóricas
"""

numericos = ['total_bill', 'size']
categoricas = ['sex', 'smoker', 'day', 'time']

df_encoded = pd.get_dummies(df, columns=categoricas, drop_first=True)

scaler = StandardScaler()
df_encoded[numericos] = scaler.fit_transform(df_encoded[numericos])

"""##División del dataset en entrenamiento y prueba."""

X = df_encoded.drop('tip', axis=1)
y = df_encoded['tip']

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Train: {x_train.shape}, Test: {x_test.shape}")

"""#Modeling (Implementación y Entrenamiento)

##Entrenar Regresion Lienal
"""

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

# Evaluación
mse= mean_squared_error(y_test, y_pred)
mae= mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'R2 Error: {r2:.2f}')
print(f'Mean Absolute Error: {mae:.2f} USD')
print(f'Mean Squared Error: {mse:.2f} USD')

"""##Entrenar Regresion KNN"""

knn_model = KNeighborsRegressor(n_neighbors=5)

knn_model.fit(x_train, y_train)

y_pred_knn = knn_model.predict(x_test)

mse_knn = mean_squared_error(y_test, y_pred_knn)
mae_knn = mean_absolute_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print(f'KNN R2 Error: {r2_knn:.2f}')
print(f'KNN Mean Absolute Error: {mae_knn:.2f} USD')
print(f'KNN Mean Squared Error: {mse_knn:.2f} USD')

"""##Visualización Modelos"""

plt.figure(figsize=(18,7))
plt.subplot(1,2,1)
sns.regplot(x=x_test['total_bill'], y=y_test, marker='o', label='Datos Reales', color='blue')
plt.scatter(x_test['total_bill'], y_pred, color='red', label='Datos de Prediccion', alpha=0.5)
plt.title('Total Cuenta vs Propina (Regresion Lineal)')
plt.xlabel('Total Cuenta')
plt.ylabel('Propina')
plt.legend()

plt.subplot(1,2,2)
sns.regplot(x=x_test['total_bill'], y=y_test, marker='o', label='Datos Reales', color='blue', scatter_kws={'alpha':0.5})
plt.scatter(x_test['total_bill'], y_pred_knn, color='green', label='Prediccion KNN', alpha=0.5)
plt.title('Total Cuenta vs Propina (KNN)')
plt.xlabel('Total Cuenta')
plt.ylabel('Propina')
plt.legend()
plt.show()